### PR TITLE
Convert final actions to revscriptsys

### LINKED ISSUE #1821: Imbuing Shrine doesn't work
Gilded Shrine is work fine on house!

Normal Imbuing Shrine doesn't work and take bug on console.

>> [Imbuement::canImbueItem] Error on search imbuement 'Dragon Hide'

image

### PR DESCRIPTION
**Pull request by dudantas**
Resolves #1821

Functions moved to Lua:
Open imbuement shrine
Open stash
Open market

### CODE REVIEW

**Comment by yatozin** [comment]
market isnt working player:sendOpenMarket() to player:openMarket() ?

**Comment by dudantas** [comment]
> market isnt working player:sendOpenMarket() to player:openMarket() ?

Fixed, thanks

File: src/luascript.cpp [hunk 1]
```diff
@@ -11588,6 +11591,20 @@ int LuaScriptInterface::luaPlayerIsOffline(lua_State* L)
...
+int LuaScriptInterface::luaPlayerOpenMarket(lua_State* L)
+{
+	// player:openMarket()
+	Player* player = getUserdata<Player>(L, 1);
+	if (!player) {
+		lua_pushnil(L);
+		return 1;
+	}
+
+	player->sendMarketEnter(player->getLastDepotId());
```
Comment (lgrossi) [inline src/luascript.cpp:11630]: Does sendMarketEnter always succeed?
If that's not the case, would be nice if it returns a value (true/false or error_type/non_error) so that we can return it to lua and properly handle it.

File: src/luascript.cpp [hunk 2]
```diff
@@ -9283,12 +9285,13 @@ int LuaScriptInterface::luaPlayerSetOfflineTrainingSkill(lua_State* L)
...
-	// player:OpenStash()
+{
+	// player:openStash()
 	Player* player = getUserdata<Player>(L, 1);
 	if (!player) {
 		return 1;
 	}
+
 	player->sendOpenStash();
 	return 1;
```
Comment (lgrossi) [inline src/luascript.cpp:9322]: Would be nice to give lua some feedbacks here (push false if no player or sendOpenStash fails, push true if it executes properly).

File: src/protocolgame.cpp [hunk 3]
```diff
@@ -3842,8 +3850,19 @@ void ProtocolGame::sendImbuementWindow(Item* item)
...
+		return;
+	}
+
 	const ItemType& it = Item::items[item->getID()];
 	uint8_t slot = it.imbuingSlots;
+	if(slot <= 0 ) {
+		player->sendTextMessage(MESSAGE_STATUS_SMALL, "This item is not imbuable.");
+		return;
+	}
+
```
Comment (lgrossi) [inline src/protocolgame.cpp:4331]: As discussed, those validations should live in player.cpp, ideally.

File: src/protocolgame.cpp [hunk 4]
```diff
@@ -3853,11 +3872,6 @@ void ProtocolGame::sendImbuementWindow(Item* item)
 		}
 	}
 
-	std::vector<Imbuement*> imbuements = g_imbuements->getImbuements(player, item);
-	if (!itemHasImbue && imbuements.empty()) {
```
Comment (lgrossi) [inline src/protocolgame.cpp:4342]: Isn't this if needed anymore?

File: src/protocolgame.cpp [hunk 5]
```diff
@@ -4166,6 +4181,10 @@ void ProtocolGame::reloadCreature(const Creature* creature)
 
 void ProtocolGame::sendOpenStash()
 {
+	if (player->getLastDepotId() == -1) {
+		return;
+  	}
+
```
Comment (lgrossi) [inline src/protocolgame.cpp]: I'd move it to player::sendOpenStash as well, since it is player logic, nothing to do with protocol.

**Review by lgrossi — CHANGES_REQUESTED** [review]
Nice one, movign actions to revscripts is a big one. Left a few comments related to giving lua better feedbacks and some moving some logic to the correct domains, but it's good in general.

File: src/protocolgame.cpp (hunk 5 above)
Comment (dudantas) [reply src/protocolgame.cpp]: Fixex on https://github.com/opentibiabr/otservbr-global/pull/1822/commits/d866087947625b1da76d3987315b9078694e0628

File: src/protocolgame.cpp (hunk 4 above)
Comment (dudantas) [reply src/protocolgame.cpp:4342]: Do not needed.

File: src/player.cpp [hunk 6]
```diff
@@ -1124,6 +1124,41 @@ void Player::sendHouseWindow(House* house, uint32_t listId) const
...
+}
+
+void Player::sendMarketEnter(uint32_t depotId)
+{
+	if (!client || !depotId) {
+		return;
+	}
+
+	if (this->getLastDepotId() == -1) {
+		return;
```
Comment (lgrossi) [inline src/player.cpp]: maybe some text message here? what does it mean if last depoit id is -1? Nothing that the player should be aware of? If its not needed, I'd just join those ifs and simplify, not need of return here:

```
	if (client && depotId && this->getLastDepotId() != -1) {
		client->sendMarketEnter(depotId);
	}
```

File: src/player.h [hunk 7]
```diff
@@ -1424,6 +1416,10 @@ class Player final : public Creature, public Cylinder
 		void sendOpenStash()
 		{
 			if (client) {
+				if (getLastDepotId() == -1) {
+					return;
+  				}
+
 				client->sendOpenStash();
 			}
```
Comment (lgrossi) [inline src/player.h:1419]: Not a big deal, but I'd simplify:

```
void sendOpenStash() {
      if (client && getLastDepotId() != -1) {
         client->sendOpenStash();
      }
}
```
Just because it remove some nesting and is easier to read.

**Review by lgrossi — APPROVED** [review]
LGTM, I added some suggestions. The return ifs are nice when you have complex functions, when you have simple ones I'd just go straightforward.

File: src/player.cpp (hunk 6 above)
Comment (dudantas) [reply src/player.cpp]: Thanks.

File: src/player.h (hunk 7 above)
Comment (dudantas) [reply src/player.h:1419]: Thanks.

**Comment by dudantas** [comment]
> LGTM, I added some suggestions. The return ifs are nice when you have complex functions, when you have simple ones I'd just go straightforward.

Thanks, great tips, I followed as you said.
