### PR TITLE
Resolves #1641 and resolves #1653

### LINKED ISSUE #1322: Hirelings dialogs not resetting properly.
**Describe the bug**
If I start the dialog with a hireling and select one of his trade options, whenever I try to use one of his other functions, like bank, switch his outfit or make him go back into his lamp, he opens the last trading option that I used.

**To Reproduce**
1. Start the dialog
2. Say Trade
3. Say Tools
4. Close the trading window.
5. Say Outfit.
6. The Tools trading option will open instead of his outfit selector.

**Expected behavior**
I should be able to select between his various skills no matter when.

### LINKED ISSUE #1641: Hireling Goods Seller
Hirelings on action Goods sell Exercise Weapons have 1 charges for 262k gold

18:48 Druid Sample [10008]: service
18:48 Andrzej: Do you want to see my goods, to access your bank account, to order food or to open your stash? If you want, I can go back to my lamp or maybe change my outfit.
18:48 Druid Sample [10008]: goods
18:48 Andrzej: I sell a selection of various items, equipment, distance weapons, wands and rods, potions, runes, supplies, tools and postal goods. Just ask!
18:48 Druid Sample [10008]: rods
18:48 Andrzej: Here you go!

### LINKED ISSUE #1653: hireling with some bugs
There are two somes when using the goods service. 

- When you buy more than 2 non stackable items (its don't happen with all non stackable items), only 1 item comes and the 
money is removed from the selected amount.

- Another problem is when you have a full backpack, even if you have another bp inside the main bp and you buy the item, you waste gold and the item isn't delivered to the character.

- In goods when you are using for example equipament and select options currency sell after you change goods for runes, you see all offers of runes (buy) with the currency sell selected. The right is change to de currency buy when you change the goods offer.

- When you select stash give a error (I believe it will be fix when the stash merges)

```
Lua Script Error: [Npc interface]
data/npc/scripts/hireling.lua:onCreatureSay
data/npc/scripts/hireling.lua:144: attempt to index global 'SupplyStash' (a nil value)
stack traceback:
        [C]: in function '__index'
        data/npc/scripts/hireling.lua:144: in function 'openPlayerStash'
        data/npc/scripts/hireling.lua:1048: in function 'callback'
        data/npc/lib/npcsystem/npchandler.lua:433: in function 'onCreatureSay'
        data/npc/scripts/hireling.lua:27: in function <data/npc/scripts/hireling.lua:26>
```

### PR DESCRIPTION
**Pull request by dudantas**
Resolves #1641 
Resolves #1653 

Resolution for the problem of the item coming with 1 charge when buying and also when buying more than 1 quantity of the same item, removed the money but was delivering 1 item
It also solves the problem of buying the item without having space in the bag and it falls to the floor

### CODE REVIEW

File: data/lib/tables/hireling_items.lua [hunk 1]
```diff
@@ -124,11 +124,11 @@ HIRELING_GOODS  =  {
 		{name = "crowbar", id = 2416, buy = 260, sell = 50},
 		{name = "dagger", id = 2379, buy = 5, sell = 2},
 		{name = "doublet", id = 2485, buy = 16, sell = 3},
-		{name = "dwarven shield", id = 2525, buy = 500, sell = 100},
-		{name = "exercise axe", id = 32385, buy = 262500, sell = 500},
-		{name = "exercise bow", id = 32387, buy = 262500, sell = 500},
-		{name = "exercise club", id = 32386, buy = 262500, sell = 500},
-		{name = "exercise sword", id = 32384, buy = 262500, sell = 500},
+		{name = "dwarven shield", id = 2525, buy = 500, sell = 100, charges = 500},
```
Comment (majestyotbr) [inline data/lib/tables/hireling_items.lua]: dwarven shield with 500 charges, lmao

**Review by attack787 — COMMENTED** [review]
Tested and it's working. Thanks!

**Review by majestyotbr — APPROVED** [review]
