### PR TITLE
Stabilizing revscriptsys monsters

### LINKED ISSUE #1807: monsters attacking from range
**Describe the bug**
some monsters are still attacking from range when they should be melee

**To Reproduce**
1. Go to 'Old Fortress'
2. Vile Granmaster , Visios Squire , Renegade knight dont come melee range to attack

**Expected behavior**
Should come to melee range to attack

### LINKED ISSUE #1877: Magic Shield stopped working
After updating from 12.40 (~3 weeks ago) to 12.51 (today latest), Magic Shield stopped working.

All damage is in life instead of mana.

The utamo vita cast run and blue circle status icon appers in status bar too.

Edit: Only with some mobs: ps.: Dragon

### LINKED ISSUE #1892: WIP: Stabilizing monsters on revscriptsys
These are mostly findings from other reports and by upgrading the ot-monster-converter:

- [x] **Fix default values for xml to lua** #1894
Values like target (update: the issue with target is actually lack of shooteffect) and targetDistance are not well fit and need to be double checked from the conversion perspective (#1807).
- [x] **Shooteffect is being set incorrectly** #1896
- [x] **Monsters are missing their specialized spells** #1898
Everything is defaulting to combat due lack of it in ot-monster-converter (see Marid for example)
- [x] **Conditions are not getting converted correctly** #1899
From the results of conversion and ot-monster-converter, ~~but I haven't had time to test~~ (edit: the conversion is ignoring conditions). I think #1865 is one sample of the symptom. #1877 looks sus also. Also, if you compare the xml monster loader and the lua, there are obvious gaps in this direction.
- [x] **Conditions are not getting loaded correctly** #1899
- [x] **Accessory conditions are not being applied** #1895
- [x] **Add flag pet** #1906
- [x] **Add flag respawnType** #1913
- [x] **Add flag passive**  #1907
- [x] **Fix speed spells** #1901
~~They might be fixed already, but I haven't checked if converter is giving a good output for this spell~~ Edit: It needs full fix, for example area effects and other details
- [x] **Fix outfit spells** #1909
~~The greatest challenge on this one is that outfits depend on the monsters names, and some monsters might request an outfit for a monster that was not yet loaded. As there's no "master list" (aka monster.xml), we either need to A. find a way to load monsters on-demand without being that hacky; B. Create the spell with the look from the monster instead of the name, but again we have no way to pre-load such info; or C. Just manually type the outfit looks into xml and make sure the monster converter gets it.~~ It's now being set on the fly. Which assumes all monsters are loaded.

[~converter]: https://img.shields.io/badge/where-monster--converter-blue
[~deserialize]: https://img.shields.io/badge/where-deserializeSpell-lightgray

And here are the list of monsters to review that got ignored on my conversion because they were either not from the original conversion (not following the format) or their current values in lua differ from the original XML, which was weird in many cases (different loots and such). These "wrongs" and etc are comparing XML vs Lua:

- [x] Faun
- [x] Dark Faun
- [ ] Pixie
- [ ] Scar Tribe Warrior
- [x] Renegade Knight
- [x] Priestess: Wrong loot (I think I missed #1861)
- [x] Marid: Wrong loot (Also #1861)
- [x] Madareth: Wrong loot
- [x] Overcharged Energy Elemental: Wrong loot
- [ ] Shard Of Magnor: Wrong ... ????
- [ ] Ripper Spectre
- [ ] Deathling Spellsinger: Voices need escaping?
- [ ] Deathling Scout: Wrong outfit?
- [ ] Energized Raging Mage: No idea what's going on on this one
- [ ] Bragrumol: Wrong loot
- [ ] Count Vlarkorth: Voices differ from xml
- [ ] Earl Osam: Voices differ from xml
- [ ] Sir Nictros: Missing creature script, incomplete?

### PR DESCRIPTION
**Pull request by debone**
Fixes #1892, #1877, #1857, #1807
Please review monsters that are on the list of #1892.

Good luck :)

### CODE REVIEW

**Review by heberholanda — APPROVED** [review]

File: data/scripts/monsters/magicals/marid.lua [hunk 1]
```diff
@@ -76,7 +78,7 @@ monster.loot = {
 	{id = "gold coin", chance = 60000, maxCount = 30},
 	{id = "blue gem", chance = 110},
 	{id = "hailstorm rod", chance = 770},
-	{id = 2070, chance = 5000},
+	{id = 2374, chance = 5000},
```
Comment (debone) [inline data/scripts/monsters/magicals/marid.lua]:
```suggestion
	{id = 2070, chance = 5000},
```

File: data/scripts/monsters/humans/priestess.lua [hunk 2]
```diff
@@ -74,7 +76,7 @@ monster.loot = {
 	{id = "talon", chance = 750},
 	{id = "hailstorm rod", chance = 1100},
 	{id = 2192, chance = 1250},
-	{id = 2070, chance = 1400},
+	{id = 2374, chance = 1400},
```
Comment (debone) [inline data/scripts/monsters/humans/priestess.lua]:
```suggestion
	{id = 2070, chance = 1400},
```

File: data/scripts/monsters/quests/the_inquisition/madareth.lua [hunk 3]
```diff
@@ -103,7 +105,7 @@ monster.loot = {
 	{id = 2169, chance = 7000},
 	{id = 8920, chance = 7000},
 	{id = 2079, chance = 7000},
-	{id = 2070, chance = 7000},
+	{id = 2374, chance = 7000},
```
Comment (debone) [inline data/scripts/monsters/quests/the_inquisition/madareth.lua]:
```suggestion
	{id = 2070, chance = 7000},
```
