### PR TITLE
The queen of the banshees quest and somes fixes in the map

### LINKED ISSUE #1684: Carlin Door
Position: 32330, 31773, 7

Door is locked, but must be normal door.

### LINKED ISSUE #1686: Forgotten Knowledge Last Boss
Missing aid 24873 on Position: 32332, 32094, 7

We cant enter the teleport since there is aid on it.

### PR DESCRIPTION
**Pull request by dudantas**
- [x] Rewrite of the "the queen of the banshees quest" to be 100% like the global
* Rewriting, converting to revscriptsys and moving the map attributes to the Lua table
Full revision in the quest and fixed various bugs:
Quest log fixed
Fixes to stay the same as the global
Converted to revscriptsys
Moved map attributes to Lua tables (startup folder)
Created a lib for banshees quest variables and settings
The queen of the banshees quest spawns fixeds

### New functions;
function Position.removeItem(...)
Removes an item from a certain position (can be used with a lever or not)

function Position.revertItem(...)
Recreates the item in a certain position, can be used with a lever or not

function Position.transformItem(...)
Transform item from position

function Position.createItem(...)
Create an item in a specific position

Registered one "lever" item walkable, id "32400"

### Bug fixes:
- [x] Resolves #1684
- [x] Resolves #1686
- Fixed Goldhanded Cultist corpse

### Map fixes:
Fixed lions sanctunm spawn and map, thanks @likeahyena
Fixed papacu map, thanks to @dracoalv
Fixed Issavi waterfall, thanks to @dracoalv
Spawns fixeds

### CODE REVIEW

File: data/lib/core/quests.lua [hunk 1]
```diff
@@ -5282,20 +5290,24 @@ end
...
-							missionId = mission.missionId,
-							missionName = self:getMissionName(questId, missionId),
-							missionDesc = self:getMissionDescription(questId, missionId)
-						}
-						missions[#missions + 1] = data
+	if questId then
+		for questId = 1, #Quests do
+			local quest = Game.getQuest(questId)
+			if quest and quest.missions then
+				if missionId then
```
Comment (andersonfaaria) [inline data/lib/core/quests.lua:5297]: esse if nunca vai ser executado pq essa variavel 'missionId' não é definida.

**Review by andersonfaaria — CHANGES_REQUESTED** [review]
Check the if I mentioned because it may be acting in an un-intended way

File: data/lib/core/quests.lua (hunk 1 above)
Comment (dudantas) [reply data/lib/core/quests.lua:5297]: Ela é, inclusive resolveu o erro que tava dando kkk
Ela é definida na tabela, eu acho que todo o erro começou justamente pq o cara que adicionou o quest tracker pensou que não precisava do if
