### PR TITLE
Map fixes

### LINKED ISSUE #1663: The Thieves Guild Quest / Bug na missão 4 e 6
**Missão 5.**

image

Essa porta ta com uma storage desatualizada gravada no mapa 

	ThievesGuild = {
		-- Reserved storage from 515206 - 51409
		Quest = 515206,
		Mission01 = 515207,
		Mission02 = 515208,
		Mission03 = 515209,
		**Mission04 = 51394,**

No caso o correto seria 51394, para poder abrir a porta. Precisa editar o mapa. 

MISSÃO O6

image

A chave que eu consegui obter pelo NPC Chantalle, deveria me teletransportar para dentro da sala, e depois desaparecer. 
O que acontece é que a porta não abre. Ficando impossuível concluir a missão. 
A tal Action ID gravada na porta é 51394, que liga a storage da missão 4, porém não fez sentido, acho que fizeram uma confusão. 
Se fosse para abrir concluindo a missão 4, seria impossível por esse tipo de porta.  

Ah... todo resto funciona, testei a quest toda. Uma delicia!

### LINKED ISSUE #2057: BUG DA ESCADA LIVRARIA DE ENERGY
#### What are the coordinates of the place where the issue with the map was found?
- X:32479
- Y:32479
- Z:12
#### Environment
OTServ Version (12.51):
Tibia Version (12.51):

### LINKED ISSUE #2196: CONTENT: Walker missing

### LINKED ISSUE #2229: MAP: i cant find ghost npc in POH from The Dream Courts Quest
#### What are the coordinates of the place where the issue with the map was found?
- X:
- Y:
- Z:

#### What kind of issue you found (respawns missing, details, large areas...)?
- 

#### Environment
- OS (e.g. Windows): 
- OTServ Version (e.g. commit): 
- Tibia Version (e.g. 12.52):

### LINKED ISSUE #2303: MAP: a uniqueid is missing from a door
#### What are the coordinates of the place where the issue with the map was found?
- X: 32908
- Y:32112
- Z:7

#### What kind of issue you found (respawns missing, details, large areas...)?
- the uniqueid (12579) is missing on the door

#### Environment
- OS (e.g. Windows): 
- OTServ Version (e.g. commit): 
- Tibia Version (e.g. 12.60): 

https://tibialatina.fandom.com/wiki/Secret_Service_Quest_(CGB)
everything else works, only that is missing

### LINKED ISSUE #2315: MAP:
## READ BEFORE PROCEEDING: OUR SERVER IS UPDATED DAILY. IF POSSIBLE MAKE SURE TO UPDATE TO THE LATEST VERSION BEFORE REPORTING.

I Have downloaded the version 30 minuts ago.

#### What are the coordinates of the place where the issue with the map was found?
- X: 32332
- Y: 32094
- Z: 7

#### What kind of issue you found (respawns missing, details, large areas...)?
- You can enter on Energy Gate leading to the Astral Shaper Boss Dungeon , but you can't return back from the Energy portal.

#### Environment
- OS (e.g. Windows): 10 home
- OTServ Version (e.g. commit):  Version 26.01.2021 - 09:17 GMT+1
- Tibia Version (e.g. 12.52): 12.61

### PR DESCRIPTION
**Pull request by dex-89**
- [X] Fixed exit teleport position (Cobra bastion: Scarlet) to 33395, 32670, 6
- [X] Fixed depot's id
- [X] Fixed city name [citizen teleport Liberty bay]
- [X] Fixed issues: #2196, #2303
- [X] Checked and fixed `Thieves guild quest` #1663 
- [X] Fix return Astral Shaper Boss Dungeon #2315 
- [X] Added PZ on Dawnport entrance
- [X] Fixed cure poison tiles action ids at Dawnport outpost entrances by @ElTeixe 
- [X] Added npc `Stricken soul` to map #2229
- [X] Added `Safe room` energetic library #2057 
- [X] Fixed doors (open/closed) in Liberty bay by @wizardlink 

**Fixed Rookgaard quests:** [#2347]
- [X] Fixed `Bear Room Quest` `To retrieve the key, use a pick on the mud floor square directly south of the big table.`
- [X] Fixed `Captain Iglues Treasure Quest` (left reward chest was not working)
- [X] Fixed `Honey flower quest` (the reward of a honey flower, not a chest)
- [X] Fixed closed door to minotaur mage (Rookgaard) now player cant open it
- [X] Added missing `dead human` [`Pick quest`] (way to `katana quest`)
- [X] Added and fixed missing items at Rookgaard (The Rookie guard quest) by @ElTeixe 
- [X] Fixed `hole -> trap` by @ElTeixe 

**Added/fixed in global update:**

Source: https://www.tibia.com/news/?subtopic=newsarchive&id=5970&fbegind=10&fbeginm=1&fbeginy=2021&fendd=9&fendm=2&fendy=2021&flist=11111111
- [X] added new item to black bert and fix item's name
- [X] added northward balcony (Fortune Wing 4 Yalahar)

**Special thanks: @ElTeixe for help**

### CODE REVIEW

**Review by paulorob-dev — APPROVED** [review]

**Review by majestyotbr — APPROVED** [review]

File: data/lib/core/storages.lua [hunk 1]
```diff
@@ -1197,7 +1197,7 @@ Storage = {
 		Mission02 = 515208,
 		Mission03 = 515209,
 		Mission04 = 51394,
-		Mission05 = 515151,
+		Mission05 = 56399,
```
Comment (dudantas) [inline data/lib/core/storages.lua]: 56395?

File: data/scripts/actions/quests/the_thieves_guild/fish_napping_key.lua [hunk 2]
```diff
@@ -1,13 +1,13 @@
...
-	end
-
 	if player:getStorageValue(Storage.ThievesGuild.Mission06) == 2 then
-		player:removeItem(8762, 1)
-		player:say('In your haste you break the key while slipping in.', TALKTYPE_MONSTER_SAY)
-		player:teleportTo(Position(32359, 32788, 6))
+		if target.actionid == 51394 and item.itemid == 8762 then
+			player:removeItem(8762, 1)
+			player:say('In your haste you break the key while slipping in.', TALKTYPE_MONSTER_SAY)
+			player:teleportTo(Position(32359, 32788, 6))
```
Comment (dudantas) [inline data/scripts/actions/quests/the_thieves_guild/fish_napping_key.lua:9]: As it was removed the check that return false, then you need to define here one return true
Otherwise, when the target is not an action id "51394" it will not send anything, it needs to send a "sorry not possible" or "you cannot use this object"

File: data/scripts/actions/quests/the_thieves_guild/fish_napping_key.lua [hunk 3]
```diff
@@ -1,13 +1,13 @@
...
+		end
 	end
 	return true
```
Comment (dudantas) [inline data/scripts/actions/quests/the_thieves_guild/fish_napping_key.lua]: Need to change to return false, I mentioned the reason above

**Review by dudantas — CHANGES_REQUESTED** [review]
