### PR TITLE
fix crash client on trade alot of items

### LINKED ISSUE #1072: Crash cliente ao vender item
**Describe the bug**
Quando você vai vender mais de 80 items no NPC o cliente trava e não responde mais.

**To Reproduce**
Faça 80 magma coat com o GM e vá vender no Rashid, quando você clicar para confirmar a venda o seu cliente vai congelar.
OBS: Qualquer item em grande quantidade vai bugar, a magma foi só um exemplo.
-
Edit: Se você comprar 100 items não estacáveis acontece a mesma coisa.

Google trans
Make 80 magma coat with the GM and go sell on Rashid, when you click to confirm the sale your customer will freeze.
NOTE: Any item in large quantities will go bad, magma was just an example.

**Screenshots**
https://prnt.sc/s4d01n

Vídeo
https://youtu.be/an3Mbmuk4YY

### PR DESCRIPTION
**Pull request by oalbsilva**
fix #1072 

credits: https://github.com/SaiyansKing/optimized_forgottenserver/commit/2ffba16ba0c70c7aab6247a3ed2a0eb9fbd6abe1

### CODE REVIEW

File: src/npc.cpp [hunk 1]
```diff
@@ -365,10 +365,11 @@ void Npc::doSayToPlayer(Player* player, const std::string& text)
 void Npc::onPlayerTrade(Player* player, int32_t callback, uint16_t itemId, uint8_t count,
 						uint8_t amount, bool ignore/* = false*/, bool inBackpacks/* = false*/)
 {
+	g_dispatcher.addTask(createTask(std::bind(&Game::updatePlayerSaleItems, &g_game, player->getID())));
```
Comment (lgrossi) [inline src/npc.cpp:372]: Always good to be safe:
if (!player) return;

**Review by lgrossi — APPROVED** [review]
lgtm, a minor comment to make it safer

File: src/npc.cpp (hunk 1 above)
Comment (oalbsilva) [reply src/npc.cpp:372]: resolved https://github.com/opentibiabr/otservbr-global/pull/1527/commits/47b926efc77070b2219fc0218800c294672d24c4
