### PR TITLE
[WIP] Several map and pack fixes/changes

### LINKED ISSUE #89: Bugs
**_--REPORTS DATA 09/04/2020_**

**Bugs encontrados:**

- [x] 1. escada n 8599 com bug no mapa
- [x] 2. quest arena - bug das portas https://github.com/opentibiabr/otservbr-global/issues/913
- [x] 3. buraco sem saida area free arrumar position: 32652 32120 11:1
- [x] 4. arrumado a porta de pedra que não abre em edron position 33177 31842 8:1
- [x] 5. arrumar porta que vai pros troll em carlin 32408 31785 7:1
- [x] 6. arrumar, que não funfou, portal que vai para boss 32915 31637 14:1   vai para: 32902 31630 14:1
- [x] 7. monstro no lugar errado Position: 33324, 32333, 13:1
- [x] 8. portal sem saida em ank 33205 32531 8:1
- [x] 9. portal do Deathbine em port hope bugado (32722 32762 8:1) ele vai para 32714 32735 8:1
- [x] 10. portas golden boots abrindo 33273 32440 12:1
- [x] 11. Position: 33562, 31775, 13: - bug portal
- [x] 12. tiles com no-logout (amarelo) positions 32785 32328 6 :1
- [x] 13. tiles com no-logout na ponte (amarelo) 32380 32179 7:1
- [x] 14. portal bugado 33167 31977 8:1

**_--REPORTS DATA 10/04/2020_**

**Bugs encontrados:**
- [x] 15. NPC Corym Ratter, que libera acesso a mission da Hidden Threats Quest, não tem script alguma, ou seja, não há como ir ao acesso, conforme video, bem como a quest está prejudicada nos demais pontos: https://www.youtube.com/watch?v=Y5G-yDI9OhM
- [x] 16. na position 33313, 32647, 6:1, era para ter o npc que trata da mission para o Boss Scarlett Etzel

**_--REPORTS DATA 11/04/2020_**

**Bugs encontrados:**
- [x] 17. oramond quest está bugada, fora entregado os pontos não surtiu efeito, e também não há o npc Doubleday's Tasks. https://www.tibiawiki.com.br/wiki/Oramond_Quest

**_--REPORTS DATA 15/04/2020_**

**Bugs encontrados:**
- [x] 18. NPC Maeryn em Grimvale, ele não inicia a missão da quest The Curse Spreads Quest. Pode ser conferido em https://www.tibiaroyal.com/br/guide/quest/272/the-curse-spreads-quest/spoiler
- [x] 19. loot do grimleech e vexclaw está muito hard, praticamente não cai os itens, bem como esses dois bixos passam por cima de energy, mas no tibia eles não passam.
- [x] 20. boss darkfang portal 33055 31910 9:1 vai para 33055 31889 9 e volta para 33054 31912 9:1
- [x] 21. boss sharpclaw portal 33128 31971 9:1 vai para 33121 31997 9 e volta para 33129 31972 9 :1
- [x] 22. boss black vixen portal 33167 31977 8:1 que vai para 33181 32012 8 e volta para 33167 31979 8:1
- [x] 23. boss obujos portal 33438 31248 11:1 tem que ir para 33420 31255 11:1 - https://forum.tibiarpgbrasil.com/uploads/monthly_2017_11/obujos.jpg.a77f08e72799ccd1b30c4095569e87de.jpg
- [x] 24. boss jaul portal 33558 31282 11 vai para 33544 31262 11 :1https://forum.tibiarpgbrasil.com/uploads/monthly_2017_11/Jaul.jpg.8f00a8357d01dc6dfe201b7dfbcc0a9e.jpg
- [x] 25. boss Tanjis portal 33648 31261 11 vai para 33640 31233 11:1https://forum.tibiarpgbrasil.com/uploads/monthly_2017_11/Tanjis.jpg.b14cb5b238bcabb409740d9a11a483d8.jpg
- [x] 26. Na position 33313, 32647, 6:1 portal para Boss Scarlett Etzel ir para position 33386 32628 7:1 e portal voltando para 33312 32647 6:1
33395 32662 6:1 saida da sala do boss da scarlet
33396 32659 6:1 entrada para sala do boss scarlet

**_--REPORTS DATA 16/04/2020_**

**Bugs encontrados:**
- [x] 27. falta adicionar esse tipo de portas id: 35608

**_--REPORTS DATA 17/04/2020_**

**Bugs encontrados:**
- [x] 28. alanvanca levou apenas um player Position: 33917, 31626, 8:1 - e position: 33918, 31646, 8:1 não tem o boss Urmahlullu the weakened
- [x] 29. npc Esrik.lua vendendo apenas 1 charge exercise weapons (o certo é 500 charges).
- [x] 30. npc Esrik.lua vendendo apenas 1 charge do stone skin amulet (o certo é 5 charges).
- [x] 31. Retro Summoner outfit GAMESTORE está OFFER_TYPE_OUTFIT_ADDON (não pode ter o ADDON).
- [x] 32. na position: 32208, 32296, 6:1, a plaquinha era para dar use e receber informações do server, se nasceu yasir, boss, conforme https://www.tibiawiki.com.br/wiki/World_Board

**_--REPORTS DATA 18/04/2020_**

**Bugs encontrados:**
- 33 Os monsters Boss, por exemplo, scarlet, bloodback, e outros em sua maioria, não estão deixando abrir o loot após matá-los.
- [x] 34. A The Secret Library Quest está bugada, não é possível passar da parte do livro, após ler o livro, era para aparecer a missão no quest log e passar para próxima etapa, contudo, voltando ao npc ele pede novamente pra ler o livro e não libera a missão seguinte. Spoiler: https://www.tibiawiki.com.br/wiki/The_Secret_Library_Quest
- [x] 35. colocar no andar da quest firewalker boots area nologout, pois tem players conseguindo, pelo lado direito, acessar o lado esquerdo e pegando a quest.
- [x] 36. boss Lady Tenebris, modificar a script, a fim de colocar a cada 15 segundos a magia que o boss puxa os players para perto, sendo a linha correta: attack name="death" interval="**15000**" chance="13" length="8" spread="0" min="-1200" max="-1500"

**_--REPORTS DATA 19/04/2020_**

**Bugs encontrados:**
- [x] 37. monster Stonerefiner não está dropando nada. Spoiler: https://www.tibiawiki.com.br/wiki/Stonerefiner
- [x] 38. npc A Sweaty Cyclops, mesmo com a quest full necessária, não está trocando iron ore por Gear Wheel, nessa parte ele está mudo e não responde.
- [x] 39. na position: 32934, 32026, 6:1 tem a rampa que desce mas não sobe.
- [x] 40. Lion's Rock Quest está bugada, na parte final de por as gemas nos 4 pontos e n aparece nem no quest log, bem como quando passar por cima de alguns sqm não aparece as mensagens, foi aberto fonte da recompensa, mas não saiu nada. Spoiler: https://www.tibiawiki.com.br/wiki/Lion%27s_Rock_Quest
- [x] 41. não há respawn de Water Buffalo no mapa. Spoiler: https://www.tibiawiki.com.br/wiki/Water_Buffalo

**_--REPORTS DATA 20/04/2020_**

**Bugs encontrados:**
- [x] 42. portal boss Black Vixen bugado, position: 33442, 32051, 9. Spoiler: https://www.tibiawiki.com.br/wiki/Black_Vixen
- [x] 43. portal boss Shadowpelt bugado, position: 33402, 32097, 9: Spoiler: https://www.tibiawiki.com.br/wiki/Shadowpelt
- [x] 44. portal position: 33429, 32083, 9 bugado, pois vai para portal position: 33064, 31977, 9 e vice versa (na hora de arrumar, colocar um sqm a frente tanto um quanto o outra pra não bugar, pois as positions é exatamente onde estão os portais).
- [x] 45. não é possível fazer Enchanted Werewolf Amulet. Spoiler: https://www.tibiawiki.com.br/wiki/Enchanted_Werewolf_Amulet

**_--REPORTS DATA 21/04/2020_**

**Bugs encontrados:**
- [x] 46. não a possibilidade de conseguir Gooey Mass na The Hive após dar use em um Insectoid Cell. Spoiler: https://www.tibiawiki.com.br/wiki/Gooey_Mass

**_--REPORTS DATA 22/04/2020_**

**Bugs encontrados:**
- 47 O Achievements não estão funcionando todos, exemplos de alguns: Após entrar pela primeira vez no covil dos Deathlings, você ganhará o Achievement "Spectulation".
"Do Not Disturb" Obtido fechando janelas 100 vezes.
 "Number of the beast" Obtido se você conseguir tirar o número "6" três vezes seguidas jogando um Dado.
Spoiler: https://www.tibiawiki.com.br/wiki/Achievements
- [x] 48. Não encontrei no projeto o evento que há no tíbia, A Piece of Cake. Spoiler: https://www.tibiawiki.com.br/wiki/A_Piece_of_Cake
- [x] 49. Não há como fazer a quest Sam's Old Backpack Quest, pois falta invasão do orc_sambackpack que dropa Old and Used Backpack. https://www.tibiaroyal.com/br/guide/quest/244/sams-old-backpack-quest/spoiler
- [x] 50. Não tem boss do Werewolf. Spoiler: https://www.tibiawiki.com.br/wiki/Werewolf

- [x] 51. retirado a pedra da POI, pois script bugou (a partir da terceira alavanca, todas travadas) 32851 32333 12:1
- [x] 52. retirada a parede da tocha em carlin, para quest cults, já que não ta funfando script 32396 31806 8:1
- [x] 53. Bug da quest blue legs, após matar o boss não está sendo possível abrir a porta da quest.,

**_--REPORTS DATA 25/04/2020_**

### LINKED ISSUE #90: NPC Kais/Nomad (Blessing) Ausentes
Os NPC's Kais/Nomad estão presentes na DataBase.
Mas não estão presentes no Game/Mapa.
Através do comando /goto não é possível encontrar
/goto kais
/goto Nomad(NPC)

Já o comando /n (funciona)
/n kais
/n nomad

### LINKED ISSUE #91: Ferumbras Ascendant Storage (Lua script error)
**Describe the bug**
Getting console errors (see screenshot) when using any of the Ferumbras Ascendant boss levers.

**To Reproduce**
1. Go to the plagirath boss room.
2. Change the lever of plagirath's room to uid 9526.
3. Use the lever.

**Expected behavior**
No console errors.

**Screenshots**
https://imgur.com/a/QPMbmW2

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
It seems that this problem is with alot of things, I however have only tested it on the bosses of the Ferumbras Ascendant Quest.

### LINKED ISSUE #92: Chest Heavy Old Tome
Uma chest que contém no global e lhe dará o item **Heavy Old Tome**, não se encontra aqui.

**Coordenada: 32348, 32194, 9** (Thaís)

**Screenshot Tibia Global:**
unknown

**Screenshot OTServBR:**
unknown (1)

### LINKED ISSUE #1005: Bugs
**_--REPORTS DATA 09/04/2020_**

**Bugs encontrados:**

- [x] 1. escada n 8599 com bug no mapa
- [x] 2. quest arena - bug das portas https://github.com/opentibiabr/otservbr-global/issues/913
- [x] 3. buraco sem saida area free arrumar position: 32652 32120 11:1
- [x] 4. arrumado a porta de pedra que não abre em edron position 33177 31842 8:1
- [x] 5. arrumar porta que vai pros troll em carlin 32408 31785 7:1
- [x] 6. arrumar, que não funfou, portal que vai para boss 32915 31637 14:1   vai para: 32902 31630 14:1
- [x] 7. monstro no lugar errado Position: 33324, 32333, 13:1
- [x] 8. portal sem saida em ank 33205 32531 8:1
- [x] 9. portal do Deathbine em port hope bugado (32722 32762 8:1) ele vai para 32714 32735 8:1
- [x] 10. portas golden boots abrindo 33273 32440 12:1
- [x] 11. Position: 33562, 31775, 13: - bug portal
- [x] 12. tiles com no-logout (amarelo) positions 32785 32328 6 :1
- [x] 13. tiles com no-logout na ponte (amarelo) 32380 32179 7:1
- [x] 14. portal bugado 33167 31977 8:1

**_--REPORTS DATA 10/04/2020_**

**Bugs encontrados:**
- [x] 15. NPC Corym Ratter, que libera acesso a mission da Hidden Threats Quest, não tem script alguma, ou seja, não há como ir ao acesso, conforme video, bem como a quest está prejudicada nos demais pontos: https://www.youtube.com/watch?v=Y5G-yDI9OhM
- [x] 16. na position 33313, 32647, 6:1, era para ter o npc que trata da mission para o Boss Scarlett Etzel

**_--REPORTS DATA 11/04/2020_**

**Bugs encontrados:**
- [x] 17. oramond quest está bugada, fora entregado os pontos não surtiu efeito, e também não há o npc Doubleday's Tasks. https://www.tibiawiki.com.br/wiki/Oramond_Quest

**_--REPORTS DATA 15/04/2020_**

**Bugs encontrados:**
- [x] 18. NPC Maeryn em Grimvale, ele não inicia a missão da quest The Curse Spreads Quest. Pode ser conferido em https://www.tibiaroyal.com/br/guide/quest/272/the-curse-spreads-quest/spoiler
- [x] 19. loot do grimleech e vexclaw está muito hard, praticamente não cai os itens, bem como esses dois bixos passam por cima de energy, mas no tibia eles não passam.
- [x] 20. boss darkfang portal 33055 31910 9:1 vai para 33055 31889 9 e volta para 33054 31912 9:1
- [x] 21. boss sharpclaw portal 33128 31971 9:1 vai para 33121 31997 9 e volta para 33129 31972 9 :1
- [x] 22. boss black vixen portal 33167 31977 8:1 que vai para 33181 32012 8 e volta para 33167 31979 8:1
- [x] 23. boss obujos portal 33438 31248 11:1 tem que ir para 33420 31255 11:1 - https://forum.tibiarpgbrasil.com/uploads/monthly_2017_11/obujos.jpg.a77f08e72799ccd1b30c4095569e87de.jpg
- [x] 24. boss jaul portal 33558 31282 11 vai para 33544 31262 11 :1https://forum.tibiarpgbrasil.com/uploads/monthly_2017_11/Jaul.jpg.8f00a8357d01dc6dfe201b7dfbcc0a9e.jpg
- [x] 25. boss Tanjis portal 33648 31261 11 vai para 33640 31233 11:1https://forum.tibiarpgbrasil.com/uploads/monthly_2017_11/Tanjis.jpg.b14cb5b238bcabb409740d9a11a483d8.jpg
- [x] 26. Na position 33313, 32647, 6:1 portal para Boss Scarlett Etzel ir para position 33386 32628 7:1 e portal voltando para 33312 32647 6:1
33395 32662 6:1 saida da sala do boss da scarlet
33396 32659 6:1 entrada para sala do boss scarlet

**_--REPORTS DATA 16/04/2020_**

**Bugs encontrados:**
- [x] 27. falta adicionar esse tipo de portas id: 35608

**_--REPORTS DATA 17/04/2020_**

**Bugs encontrados:**
- [x] 28. alanvanca levou apenas um player Position: 33917, 31626, 8:1 - e position: 33918, 31646, 8:1 não tem o boss Urmahlullu the weakened
- [x] 29. npc Esrik.lua vendendo apenas 1 charge exercise weapons (o certo é 500 charges).
- [x] 30. npc Esrik.lua vendendo apenas 1 charge do stone skin amulet (o certo é 5 charges).
- [x] 31. Retro Summoner outfit GAMESTORE está OFFER_TYPE_OUTFIT_ADDON (não pode ter o ADDON).
- [x] 32. na position: 32208, 32296, 6:1, a plaquinha era para dar use e receber informações do server, se nasceu yasir, boss, conforme https://www.tibiawiki.com.br/wiki/World_Board

**_--REPORTS DATA 18/04/2020_**

**Bugs encontrados:**
- 33 Os monsters Boss, por exemplo, scarlet, bloodback, e outros em sua maioria, não estão deixando abrir o loot após matá-los.
- [x] 34. A The Secret Library Quest está bugada, não é possível passar da parte do livro, após ler o livro, era para aparecer a missão no quest log e passar para próxima etapa, contudo, voltando ao npc ele pede novamente pra ler o livro e não libera a missão seguinte. Spoiler: https://www.tibiawiki.com.br/wiki/The_Secret_Library_Quest
- [x] 35. colocar no andar da quest firewalker boots area nologout, pois tem players conseguindo, pelo lado direito, acessar o lado esquerdo e pegando a quest.
- [x] 36. boss Lady Tenebris, modificar a script, a fim de colocar a cada 15 segundos a magia que o boss puxa os players para perto, sendo a linha correta: attack name="death" interval="**15000**" chance="13" length="8" spread="0" min="-1200" max="-1500"

**_--REPORTS DATA 19/04/2020_**

**Bugs encontrados:**
- [x] 37. monster Stonerefiner não está dropando nada. Spoiler: https://www.tibiawiki.com.br/wiki/Stonerefiner
- [x] 38. npc A Sweaty Cyclops, mesmo com a quest full necessária, não está trocando iron ore por Gear Wheel, nessa parte ele está mudo e não responde.
- [x] 39. na position: 32934, 32026, 6:1 tem a rampa que desce mas não sobe.
- [x] 40. Lion's Rock Quest está bugada, na parte final de por as gemas nos 4 pontos e n aparece nem no quest log, bem como quando passar por cima de alguns sqm não aparece as mensagens, foi aberto fonte da recompensa, mas não saiu nada. Spoiler: https://www.tibiawiki.com.br/wiki/Lion%27s_Rock_Quest
- [x] 41. não há respawn de Water Buffalo no mapa. Spoiler: https://www.tibiawiki.com.br/wiki/Water_Buffalo

**_--REPORTS DATA 20/04/2020_**

**Bugs encontrados:**
- [x] 42. portal boss Black Vixen bugado, position: 33442, 32051, 9. Spoiler: https://www.tibiawiki.com.br/wiki/Black_Vixen
- [x] 43. portal boss Shadowpelt bugado, position: 33402, 32097, 9: Spoiler: https://www.tibiawiki.com.br/wiki/Shadowpelt
- [x] 44. portal position: 33429, 32083, 9 bugado, pois vai para portal position: 33064, 31977, 9 e vice versa (na hora de arrumar, colocar um sqm a frente tanto um quanto o outra pra não bugar, pois as positions é exatamente onde estão os portais).
- [x] 45. não é possível fazer Enchanted Werewolf Amulet. Spoiler: https://www.tibiawiki.com.br/wiki/Enchanted_Werewolf_Amulet

**_--REPORTS DATA 21/04/2020_**

**Bugs encontrados:**
- [x] 46. não a possibilidade de conseguir Gooey Mass na The Hive após dar use em um Insectoid Cell. Spoiler: https://www.tibiawiki.com.br/wiki/Gooey_Mass

**_--REPORTS DATA 22/04/2020_**

**Bugs encontrados:**
- 47 O Achievements não estão funcionando todos, exemplos de alguns: Após entrar pela primeira vez no covil dos Deathlings, você ganhará o Achievement "Spectulation".
"Do Not Disturb" Obtido fechando janelas 100 vezes.
 "Number of the beast" Obtido se você conseguir tirar o número "6" três vezes seguidas jogando um Dado.
Spoiler: https://www.tibiawiki.com.br/wiki/Achievements
- [x] 48. Não encontrei no projeto o evento que há no tíbia, A Piece of Cake. Spoiler: https://www.tibiawiki.com.br/wiki/A_Piece_of_Cake
- [x] 49. Não há como fazer a quest Sam's Old Backpack Quest, pois falta invasão do orc_sambackpack que dropa Old and Used Backpack. https://www.tibiaroyal.com/br/guide/quest/244/sams-old-backpack-quest/spoiler
- [x] 50. Não tem boss do Werewolf. Spoiler: https://www.tibiawiki.com.br/wiki/Werewolf

- [x] 51. retirado a pedra da POI, pois script bugou (a partir da terceira alavanca, todas travadas) 32851 32333 12:1
- [x] 52. retirada a parede da tocha em carlin, para quest cults, já que não ta funfando script 32396 31806 8:1
- [x] 53. Bug da quest blue legs, após matar o boss não está sendo possível abrir a porta da quest.,

**_--REPORTS DATA 25/04/2020_**

### LINKED ISSUE #1025: NPC Kais/Nomad (Blessing) Ausentes
Os NPC's Kais/Nomad estão presentes na DataBase.
Mas não estão presentes no Game/Mapa.
Através do comando /goto não é possível encontrar
/goto kais
/goto Nomad(NPC)

Já o comando /n (funciona)
/n kais
/n nomad

### LINKED ISSUE #1032: Ferumbras Ascendant Storage (Lua script error)
**Describe the bug**
Getting console errors (see screenshot) when using any of the Ferumbras Ascendant boss levers.

**To Reproduce**
1. Go to the plagirath boss room.
2. Change the lever of plagirath's room to uid 9526.
3. Use the lever.

**Expected behavior**
No console errors.

**Screenshots**
https://imgur.com/a/QPMbmW2

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
It seems that this problem is with alot of things, I however have only tested it on the bosses of the Ferumbras Ascendant Quest.

### LINKED ISSUE #1037: Chest Heavy Old Tome
Uma chest que contém no global e lhe dará o item **Heavy Old Tome**, não se encontra aqui.

**Coordenada: 32348, 32194, 9** (Thaís)

**Screenshot Tibia Global:**
unknown

**Screenshot OTServBR:**
unknown (1)

### PR DESCRIPTION
**Pull request by dudantas**
Created new areas on the map:
- orcsoberfest (all credits to the @lucaslking)
- High level blessings (@dudantas)
- Several pieces of hunts missing and other fixes in existing areas (@dudantas and @lucaslking)

Bug fixes:
- All towns and houses were redone from 0 (full credit to @lucaslking )
- All key doors were revised on the map, correcting several doors that should not open and others that should not open and open.
- Fixed sell bug in the npc Esrik
- Fixed items names and attributes in the items.xml
- Fixed doors in the door.lua table
- Fixed several map bug less in quests that were not cataloged in the issues
- Resolves #1005
- Resolves #1025
- Resolves #1032
- Resolves #1037

Changes:
- Defined action 100 for unmoveable items
- Defined action 101 for use pick tiles
- Defined action 102 for wells
All actions on the map have been redefined to use these.

Added:
- Script for creating quests through the action_unique table.
- Initial storages table organized in order of update of each quest, where it will be used to recreate all the quests.

### CODE REVIEW

File: data/global.lua [hunk 1]
```diff
@@ -3,7 +3,7 @@
 math.randomseed(os.time())
 dofile('data/lib/lib.lua')
 
-NOT_MOVEABLE_ACTION = 8000
```
Comment (jlcvp) [inline data/global.lua:6]: did you search everywhere if this wasn't hardcoded?

File: data/lib/core/storages.lua [hunk 2]
```diff
@@ -3,18 +3,600 @@
 -- Sort it in Values -
```
Comment (jlcvp) [inline data/lib/core/storages.lua:4]: all these new empty tables will use more stack memory to instantiate

File: data/movements/scripts/others/teleports/roshamuulCarpet.lua [hunk 3]
```diff
@@ -4,7 +4,7 @@ function onStepIn(creature, item, position, fromPosition)
 		return true
 	end
 
-	local town = Town(2)
+	local town = Town(8)
```
Comment (jlcvp) [inline data/movements/scripts/others/teleports/roshamuulCarpet.lua:7]: [enhancement] it would be great to have an Enum describing the Town values

**Review by jlcvp — COMMENTED** [review]
LGTM

File: data/movements/scripts/others/teleports/roshamuulCarpet.lua (hunk 3 above)
Comment (dudantas) [reply data/movements/scripts/others/teleports/roshamuulCarpet.lua:7]: It is true, in your opinion, where could it be?

File: data/global.lua (hunk 1 above)
Comment (dudantas) [reply data/global.lua:6]: Yes, I have not found any quotes for use.

File: data/lib/core/storages.lua (hunk 2 above)
Comment (dudantas) [reply data/lib/core/storages.lua:4]: > all these new empty tables will use more stack memory to instantiate

Yes, I am aware.
I added it to make the organization easier for me, since I will start to develop all the quests and review the existing ones. One by one in order of update and reviewing the number of storages, creating an order for them, this will make it easier for me.

File: data/scripts/movements/quests/deeplings worldchange/jaul.lua [hunk 4]
```diff
@@ -0,0 +1,22 @@
+local enterPosition = {x = 33543, y = 31263, z = 11}
```
Comment (gpedro) [inline data/scripts/movements/quests/deeplings worldchange/jaul.lua]: this can be merged with another scripts like obujos and tanjis by using some tables.

Comment (dudantas) [reply data/scripts/movements/quests/deeplings worldchange/jaul.lua]: The script is not mine, I just renamed the file, but I went up the refactoring at https://github.com/opentibiabr/otservbr-global/pull/1059/commits/78c3be10b79c79033e73d03fcfbb883b07763968
